### ISSUE TITLE
Implicit dependency on SB-BSD-SOCKETS

### ISSUE THREAD

**Issue by quicklisp** [brianjcj/telnetlib-for-common-lisp#1]
telnetlib references symbols from sb-bsd-sockets, but does not explicitly have it in the :depends-on list in its system definition. sb-bsd-sockets is often loaded already via slime/swank, but it's not part of a plain sbcl session by default. In a plain sbcl session, building telnetlib fails with this error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10044775D3}>: The name "SB-BSD-SOCKETS" does not designate any package.
```

The fix is to add something like #+sbcl :sb-bsd-sockets to the :depends-on list in the system definition.

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2014-12-02/failure-report/telnetlib.html#telnetlib has some additional info.

**Comment by brianjcj** [comment]
Hi Zach, could you send me a pull request for the changes? :)

**Comment by quicklisp** [comment]
Ok, I did that.

**Comment by brianjcj** [comment]
Merged. Thanks Zach!
